
POST http://localhost:3000/users/
Content-Type: application/json

{
    "username":"uday",
    "password":"uday@538"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"deven",
    "password":"deven@537"
}


###

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldmVuIiwiaWF0IjoxNjQxNDQwOTU0fQ.Yc-3zbpEvXZ-panYyAzSD6hvJZQv2bLlj1SqBYMRIOY


###